version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
       - .:/var/www/html:delegated
    networks:
      - app-network
    depends_on:
      - db
      - redis
    command: ["sh", "-c", "/usr/local/bin/wait-for-it.sh db:3306 --  ${COMMAND} /usr/local/bin/start_prod.sh"]
  db:
    image: mysql:8.0.37
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: gym
      MYSQL_USER: user_gym
      MYSQL_PASSWORD: password_gym
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ../database/gym:/var/lib/mysql
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: gym-redis
    restart: unless-stopped
    ports:
      - "6378:6379"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html:delegated
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
