services:
  app:
    build:
      context: .
    depends_on:
      - db
      - redis
    volumes: 
      - .:/app
      - /app/vendor
    ports:
      - "${APP_PORT:-8001}:8000"
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: gym
      DB_USERNAME: user_gym
      DB_PASSWORD: password_gym
    command: ["sh", "-c", "/usr/local/bin/wait-for-it.sh db:3306 --  /usr/local/bin/start_dev.sh"]
  db:
    image: mysql:8.0.37
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: gym
      MYSQL_USER: user_gym
      MYSQL_PASSWORD: password_gym
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ../database/gym:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: gym-redis
    restart: unless-stopped
    ports:
      - "6378:6379"
