services:
  app:
    build:
      context: .
    depends_on:
      - db
    volumes: 
      - .:/app
      - /app/vendor
    ports:
      - 8001:8000
    command: ["sh", "-c", "php artisan key:generate --force &&sleep 15 && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"]
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: gym
      DB_USERNAME: user_gym
      DB_PASSWORD: password_gym


  db:
    image: mysql:8.0.37
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: gym
      MYSQL_USER: user_gym
      MYSQL_PASSWORD: password_gym
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ~/database/gym:/var/lib/mysql
