version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    networks:
      - app-network



  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
